### ISSUE TITLE
Error: not a number: buffer[42910] = 18

### ISSUE THREAD

**Issue by caryyu** [themasch/node-bencode#95]
Reference: https://github.com/caryyu/bteye/blob/bencode-experiment/test/bencode.test.js

# Exception 
```txt
/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:44
    throw new Error('not a number: buffer[' + i + '] = ' + num)
    ^

Error: not a number: buffer[42910] = 18
    at getIntFromBuffer (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:44:11)
    at Function.decode.buffer (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:160:16)
    at Function.decode.dictionary (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:127:17)
    at Function.decode.next (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:94:21)
    at Function.decode.dictionary (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:127:36)
    at Function.decode.next (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:94:21)
    at Object.decode (/Users/caryyu/Desktop/bteye/node_modules/bencode/lib/decode.js:83:17)
    at Request._callback (/Users/caryyu/Desktop/bteye/test/bencode.test.js:10:24)
    at Request.self.callback (/Users/caryyu/Desktop/bteye/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
```

# Reproduce

Git-check out the referred the repo above, and then execute the following commands

```shell
npm i
node test/bencode.test.js
```

**Comment by jhermsmeier** [comment]
That particular torrent file parses fine for me with `bencode` – I think you might need to set `request`'s option `encoding: null` to receive the response body as a Buffer instead of whatever it's defaulting to, as that might be mangling your response body.

**Comment by caryyu** [comment]
@jhermsmeier It worked, thanks a lot
